### ISSUE TITLE
How does filter work?

### ISSUE THREAD

**Issue by jyotman** [Hacklone/arraync#2]
This is my code - 
 ```
'use strict';

const arraync = require('arraync');

function greaterThan3(num){
	return new Promise(function(resolve, reject){
		setTimeout(function(){
			resolve(num > 3);
		}, 1000);
	});
}

var numbers = [1,2,3,4,5];

(async()=>{
	const ans = await numbers.filterAsync(await greaterThan3Async);
	console.log(ans);
})();
```

I'm trying to filter the array using an async function but this is what I get as output - 

    [ false, false, false, true, true ]

Also I get this same output when I use `mapAsync` instead of `filterAsync`. 

How do I get the output - 

    [4, 5]

**Comment by Hacklone** [comment]
Hey,

I think the problem is that you've put an additional await in the filterAsync:
Try changing:
```
const ans = await numbers.filterAsync(await greaterThan3Async);
```
to
```
const ans = await numbers.filterAsync(greaterThan3Async);
```

Hope this helps 👍 

Barna

**Comment by jyotman** [comment]
Hi, its working correct both the ways. Think I must have made some mistake before.

Thanks for the help!
